# Generated by Django 6.0.2 on 2026-03-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompteEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.IntegerField()),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('mot_de_passe', models.CharField(max_length=100)),
                ('adresse_mail', models.EmailField(max_length=254)),
                ('telephone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_projet', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('file_path', models.FileField(upload_to='files/', verbose_name='')),
                ('participants', models.ManyToManyField(to='PP.compteetudiant')),
            ],
        ),
    ]
