# Generated by Django 6.0.2 on 2026-02-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buisness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_projet', models.CharField(max_length=100)),
                ('adresse_siege_social', models.CharField(max_length=200)),
                ('formeJuridique', models.CharField(choices=[('SARL', 'Sarl'), ('EURL', 'Eurl')])),
                ('activite', models.CharField(max_length=200)),
                ('numero_registre_commerce', models.IntegerField()),
                ('copie_registre_commerce', models.ImageField(upload_to='file')),
                ('numero_identification_fiscale', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('nom_projet', models.CharField(max_length=100)),
                ('adresse_mail', models.EmailField(max_length=254)),
                ('telephone', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
