# Generated by Django 6.0.2 on 2026-02-20 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buisness',
            name='copie_registre_commerce',
        ),
    ]
