# Generated by Django 6.0.2 on 2026-03-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Besoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeDeBesoin', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('statut', models.CharField(choices=[('NonVue', 'Non Vue'), ('EnAttente', 'En Attente'), ('Accepte', 'Accepte'), ('Refuse', 'Refuse'), ('DocumentManquant', 'Document Maquant')], default='NonVue', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='CompteAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('mot_de_passe', models.CharField()),
                ('adresse_mail', models.EmailField(max_length=254)),
                ('telephone', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='projet',
            name='statut',
            field=models.CharField(choices=[('NonVue', 'Non Vue'), ('EnAttente', 'En Attente'), ('Accepte', 'Accepte'), ('Refuse', 'Refuse'), ('DocumentManquant', 'Document Maquant')], default='NonVue', max_length=16),
        ),
    ]
