# Generated by Django 6.0.2 on 2026-03-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0002_besoin_compteadmin_projet_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='besoin',
            name='participants',
            field=models.ManyToManyField(to='PP.compteetudiant'),
        ),
    ]
