# Generated by Django 6.0.2 on 2026-02-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0002_remove_buisness_copie_registre_commerce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='adresse_mail',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='telephone',
        ),
        migrations.CreateModel(
            name='CompteEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('adresse_mail', models.EmailField(max_length=254)),
                ('telephone', models.IntegerField()),
                ('liste_de_projet', models.ManyToManyField(to='PP.projet')),
            ],
        ),
    ]
