# Generated by Django 6.0.2 on 2026-02-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0003_remove_projet_adresse_mail_remove_projet_nom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compteetudiant',
            name='liste_de_projet',
        ),
        migrations.AddField(
            model_name='projet',
            name='participants',
            field=models.ManyToManyField(to='PP.compteetudiant'),
        ),
    ]
