# Generated by Django 6.0.2 on 2026-02-24 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0004_remove_compteetudiant_liste_de_projet_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='buisness',
        ),
    ]
