# Generated by Django 6.0.2 on 2026-02-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0005_delete_buisness'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='file_path',
            field=models.FileField(default='settings.MEDIA_ROOT/TypeC.pdf', upload_to='files/', verbose_name=''),
        ),
    ]
