# Generated by Django 6.0.2 on 2026-02-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0006_projet_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='compteetudiant',
            name='mot_de_passe',
            field=models.CharField(default='quarantes douze', max_length=100),
            preserve_default=False,
        ),
    ]
