# Generated by Django 6.0.2 on 2026-02-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0007_compteetudiant_mot_de_passe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='file_path',
            field=models.FileField(upload_to='files/', verbose_name=''),
        ),
    ]
