# Generated by Django 6.0.2 on 2026-02-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0008_alter_projet_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='compteetudiant',
            name='matricule',
            field=models.IntegerField(default='33009412'),
            preserve_default=False,
        ),
    ]
