# Generated by Django 6.0.2 on 2026-02-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0009_compteetudiant_matricule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compteetudiant',
            name='matricule',
            field=models.IntegerField(unique=True),
        ),
    ]
