# Generated by Django 6.0.2 on 2026-02-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0010_alter_compteetudiant_matricule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compteetudiant',
            name='id',
        ),
        migrations.AlterField(
            model_name='compteetudiant',
            name='matricule',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
