# Generated by Django 6.0.2 on 2026-02-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0011_remove_compteetudiant_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compteetudiant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='compteetudiant',
            name='matricule',
            field=models.IntegerField(),
        ),
    ]
