# Generated by Django 6.0.2 on 2026-02-27 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PP', '0012_compteetudiant_id_alter_compteetudiant_matricule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compteetudiant',
            name='matricule',
        ),
    ]
